package com.dennyac.twirp.protoc;

import com.google.protobuf.DescriptorProtos.FileDescriptorProto;
import com.google.protobuf.DescriptorProtos.MethodDescriptorProto;
import com.google.protobuf.DescriptorProtos.ServiceDescriptorProto;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;

import javax.lang.model.element.Modifier;
import java.util.Objects;

/**
 * Emits the client-side Jersey stub for a Twirp service.
 *
 * <p>The generated class:
 * <ul>
 *   <li>Implements the service interface emitted by {@link ServiceGenerator}.</li>
 *   <li>Takes a base {@code WebTarget} (any prefix the caller likes — typically
 *       the root of the remote application) and a wire content type.</li>
 *   <li>Registers the standard Twirp body providers on the supplied target via
 *       {@link com.dennyac.twirp.TwirpClients#registerProviders}, so callers
 *       can use a plain {@code JerseyClientBuilder} without further wiring.</li>
 *   <li>Routes every call through {@link com.dennyac.twirp.TwirpClients#invoke}
 *       so non-2xx responses are decoded as {@link com.dennyac.twirp.TwirpException}
 *       instances rather than leaky {@code WebApplicationException}s.</li>
 * </ul>
 *
 * <p>The default content type is {@code application/protobuf}; pass the
 * two-arg constructor with {@link com.dennyac.twirp.TwirpMediaTypes#APPLICATION_JSON}
 * to switch to the JSON wire format.
 *
 * <p>When the {@code clientBuilder} option is enabled, the class also gains a
 * static {@code builder(Environment, JerseyClientConfiguration)} factory that
 * returns a {@link com.dennyac.twirp.TwirpClientBuilder} wired to a managed
 * {@code dropwizard-client}. It is off by default so the generated client stays
 * dependency-light (the {@code WebTarget} constructors only need the JAX-RS API).
 */
final class ClientGenerator {

    private static final ClassName WEB_TARGET =
            ClassName.get("jakarta.ws.rs.client", "WebTarget");
    private static final ClassName ENTITY =
            ClassName.get("jakarta.ws.rs.client", "Entity");
    private static final ClassName TWIRP_CLIENTS =
            ClassName.get("com.dennyac.twirp", "TwirpClients");
    private static final ClassName TWIRP_EXCEPTION =
            ClassName.get("com.dennyac.twirp", "TwirpException");
    private static final ClassName TWIRP_MEDIA_TYPES =
            ClassName.get("com.dennyac.twirp", "TwirpMediaTypes");
    private static final ClassName TWIRP_CLIENT_BUILDER =
            ClassName.get("com.dennyac.twirp", "TwirpClientBuilder");
    private static final ClassName TWIRP_CONTEXT =
            ClassName.get("com.dennyac.twirp", "TwirpContext");
    private static final ClassName ENVIRONMENT =
            ClassName.get("io.dropwizard.core.setup", "Environment");
    private static final ClassName JERSEY_CLIENT_CONFIGURATION =
            ClassName.get("io.dropwizard.client", "JerseyClientConfiguration");
    private static final ClassName STRING = ClassName.get(String.class);
    private static final ClassName OBJECTS = ClassName.get(Objects.class);

    private final Options options;
    private final TypeMapper types;

    ClientGenerator(Options options, TypeMapper types) {
        this.options = options;
        this.types = types;
    }

    TypeSpec generateClient(FileDescriptorProto file, ServiceDescriptorProto service,
                            ClassName serviceInterface) {
        String servicePath = buildServicePath(file, service);
        String clientName = service.getName() + "Client";

        TypeSpec.Builder cls = TypeSpec.classBuilder(clientName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(serviceInterface)
                .addJavadoc("Jersey client for the {@code $L} Twirp service.\n"
                                + "\n<p>POSTs to {@code $L/<Method>} on the supplied base {@code WebTarget}, "
                                + "using either {@code application/protobuf} or {@code application/json} "
                                + "as the wire format.\n"
                                + "\n<p>Generated by jaxrs-twirp-protoc — do not edit by hand.\n",
                        service.getName(), servicePath);

        cls.addField(FieldSpec.builder(WEB_TARGET, "target",
                Modifier.PRIVATE, Modifier.FINAL).build());
        cls.addField(FieldSpec.builder(STRING, "contentType",
                Modifier.PRIVATE, Modifier.FINAL).build());

        if (options.generateClientBuilder()) {
            ClassName self = ClassName.get(serviceInterface.packageName(), clientName);
            cls.addMethod(MethodSpec.methodBuilder("builder")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .returns(ParameterizedTypeName.get(TWIRP_CLIENT_BUILDER, self))
                    .addParameter(ENVIRONMENT, "environment")
                    .addParameter(JERSEY_CLIENT_CONFIGURATION, "configuration")
                    .addJavadoc("Start a fluent builder backed by a managed {@code dropwizard-client}.\n"
                                    + "\n<p>Set the remote {@code baseUri} and (optionally) the wire format, then\n"
                                    + "call {@code build()}:\n"
                                    + "\n<pre>{@code\n"
                                    + "$L client = $L.builder(environment, configuration)\n"
                                    + "        .baseUri(\"https://host\")\n"
                                    + "        .json()\n"
                                    + "        .build();\n"
                                    + "}</pre>\n"
                                    + "\n<p>Requires {@code io.dropwizard:dropwizard-client} on the classpath. For a\n"
                                    + "client you build yourself, use a constructor or {@link $T} directly.\n",
                            clientName, clientName, TWIRP_CLIENT_BUILDER)
                    .addStatement("return $T.forService($T::new)\n"
                                    + "    .using(environment, configuration)\n"
                                    + "    .clientName($S)",
                            TWIRP_CLIENT_BUILDER, self, clientName)
                    .build());
        }

        cls.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(WEB_TARGET, "baseTarget")
                .addJavadoc("Construct a client that uses {@code application/protobuf} as the wire format.\n")
                .addStatement("this(baseTarget, $T.APPLICATION_PROTOBUF)", TWIRP_MEDIA_TYPES)
                .build());

        cls.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(WEB_TARGET, "baseTarget")
                .addParameter(STRING, "contentType")
                .addJavadoc("Construct a client that uses the supplied content type as the wire format.\n"
                                + "\n@param baseTarget any {@code WebTarget} whose root the server is at\n"
                                + "@param contentType one of {@link $T#APPLICATION_PROTOBUF} or "
                                + "{@link $T#APPLICATION_JSON}\n",
                        TWIRP_MEDIA_TYPES, TWIRP_MEDIA_TYPES)
                .addStatement("$T.requireNonNull(baseTarget, $S)", OBJECTS, "baseTarget")
                .addStatement("$T.requireNonNull(contentType, $S)", OBJECTS, "contentType")
                .addStatement("$T.registerProviders(baseTarget)", TWIRP_CLIENTS)
                .addStatement("this.target = baseTarget.path($S)", servicePath)
                .addStatement("this.contentType = contentType")
                .build());

        for (MethodDescriptorProto method : service.getMethodList()) {
            cls.addMethod(generateClientMethod(method));
        }
        return cls.build();
    }

    private String buildServicePath(FileDescriptorProto file, ServiceDescriptorProto service) {
        StringBuilder sb = new StringBuilder(options.pathPrefix());
        if (!sb.toString().endsWith("/")) {
            sb.append('/');
        }
        if (!file.getPackage().isEmpty()) {
            sb.append(file.getPackage()).append('.');
        }
        sb.append(service.getName());
        return sb.toString();
    }

    private MethodSpec generateClientMethod(MethodDescriptorProto method) {
        ClassName input = types.resolve(method.getInputType());
        ClassName output = types.resolve(method.getOutputType());
        String protoMethodName = method.getName();
        String javaMethodName = JavaNaming.lowerCamelMethodName(protoMethodName);

        MethodSpec.Builder builder = MethodSpec.methodBuilder(javaMethodName)
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(output)
                .addParameter(input, "request");
        if (options.generateContext()) {
            builder.addParameter(TWIRP_CONTEXT, "context");
        }
        builder.addException(TWIRP_EXCEPTION);

        if (options.generateContext()) {
            builder.addStatement("return $T.invoke(\n"
                            + "    $T.applyHeaders(target.path($S).request(contentType).accept(contentType), context),\n"
                            + "    $T.entity(request, contentType),\n"
                            + "    $T.class)",
                    TWIRP_CLIENTS, TWIRP_CLIENTS, "/" + protoMethodName, ENTITY, output);
        } else {
            builder.addStatement("return $T.invoke(\n"
                            + "    target.path($S).request(contentType).accept(contentType),\n"
                            + "    $T.entity(request, contentType),\n"
                            + "    $T.class)",
                    TWIRP_CLIENTS, "/" + protoMethodName, ENTITY, output);
        }
        return builder.build();
    }
}
