# Copyright 2026 the jaxrs-twirp authors
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
