package io.dropwizard.twirp.protoc;

import com.google.protobuf.DescriptorProtos.FileDescriptorProto;
import com.google.protobuf.DescriptorProtos.MethodDescriptorProto;
import com.google.protobuf.DescriptorProtos.ServiceDescriptorProto;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import javax.lang.model.element.Modifier;
import java.util.Objects;

/**
 * Emits the JAX-RS {@code @Path}-annotated resource class for a Twirp service.
 *
 * <p>The generated class:
 * <ul>
 *   <li>Is annotated {@code @Path("/<prefix>/<package>.<Service>")}.</li>
 *   <li>Constructor-injects an instance of the generated service interface.</li>
 *   <li>Exposes one {@code @POST}-annotated method per RPC, accepting and
 *       producing both {@code application/protobuf} and {@code application/json}.</li>
 *   <li>Wraps each call in {@link io.dropwizard.twirp.TwirpInvocations#invoke}
 *       so that any unhandled exception becomes a Twirp {@code internal} error
 *       instead of a leaky 500.</li>
 * </ul>
 *
 * <p>RPC URL path segments use the original proto method name (UpperCamelCase),
 * matching the Twirp wire spec. Java method names are lowerCamelCase to match
 * the interface generated by {@link ServiceGenerator}.
 */
final class ResourceGenerator {

    private static final ClassName JAX_PATH = ClassName.get("jakarta.ws.rs", "Path");
    private static final ClassName JAX_POST = ClassName.get("jakarta.ws.rs", "POST");
    private static final ClassName JAX_CONSUMES = ClassName.get("jakarta.ws.rs", "Consumes");
    private static final ClassName JAX_PRODUCES = ClassName.get("jakarta.ws.rs", "Produces");
    private static final ClassName OBJECTS = ClassName.get(Objects.class);
    private static final ClassName TWIRP_INVOCATIONS =
            ClassName.get("io.dropwizard.twirp", "TwirpInvocations");
    private static final ClassName TWIRP_MEDIA_TYPES =
            ClassName.get("io.dropwizard.twirp", "TwirpMediaTypes");

    private final Options options;
    private final TypeMapper types;

    ResourceGenerator(Options options, TypeMapper types) {
        this.options = options;
        this.types = types;
    }

    TypeSpec generateResource(FileDescriptorProto file, ServiceDescriptorProto service,
                              ClassName serviceInterface) {
        String classPath = buildClassPath(file, service);

        TypeSpec.Builder cls = TypeSpec.classBuilder(service.getName() + "Resource")
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addAnnotation(AnnotationSpec.builder(JAX_PATH)
                        .addMember("value", "$S", classPath).build())
                .addJavadoc("JAX-RS resource exposing the {@code $L} Twirp service over "
                                + "{@code POST $L/<Method>}.\n"
                                + "\n<p>Generated by dropwizard-twirp-protoc — do not edit by hand.\n",
                        service.getName(), classPath);

        cls.addField(FieldSpec.builder(serviceInterface, "service",
                        Modifier.PRIVATE, Modifier.FINAL)
                .build());

        cls.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(serviceInterface, "service")
                .addStatement("this.service = $T.requireNonNull(service, $S)", OBJECTS, "service")
                .build());

        for (MethodDescriptorProto method : service.getMethodList()) {
            cls.addMethod(generateResourceMethod(method));
        }
        return cls.build();
    }

    private String buildClassPath(FileDescriptorProto file, ServiceDescriptorProto service) {
        StringBuilder sb = new StringBuilder(options.pathPrefix());
        if (!sb.toString().endsWith("/")) {
            sb.append('/');
        }
        if (!file.getPackage().isEmpty()) {
            sb.append(file.getPackage()).append('.');
        }
        sb.append(service.getName());
        return sb.toString();
    }

    private MethodSpec generateResourceMethod(MethodDescriptorProto method) {
        ClassName input = types.resolve(method.getInputType());
        ClassName output = types.resolve(method.getOutputType());
        String protoMethodName = method.getName();
        String javaMethodName = JavaNaming.lowerCamelMethodName(protoMethodName);

        AnnotationSpec consumes = AnnotationSpec.builder(JAX_CONSUMES)
                .addMember("value", "{$T.APPLICATION_PROTOBUF, $T.APPLICATION_JSON}",
                        TWIRP_MEDIA_TYPES, TWIRP_MEDIA_TYPES)
                .build();
        AnnotationSpec produces = AnnotationSpec.builder(JAX_PRODUCES)
                .addMember("value", "{$T.APPLICATION_PROTOBUF, $T.APPLICATION_JSON}",
                        TWIRP_MEDIA_TYPES, TWIRP_MEDIA_TYPES)
                .build();

        return MethodSpec.methodBuilder(javaMethodName)
                .addModifiers(Modifier.PUBLIC)
                .returns(output)
                .addParameter(input, "request")
                .addAnnotation(JAX_POST)
                .addAnnotation(AnnotationSpec.builder(JAX_PATH)
                        .addMember("value", "$S", "/" + protoMethodName).build())
                .addAnnotation(consumes)
                .addAnnotation(produces)
                .addStatement("return $T.invoke($S, () -> service.$L(request))",
                        TWIRP_INVOCATIONS, protoMethodName, javaMethodName)
                .build();
    }
}
