package com.dennyac.twirp.example;

import io.dropwizard.client.JerseyClientBuilder;
import io.dropwizard.client.JerseyClientConfiguration;
import io.dropwizard.testing.ConfigOverride;
import io.dropwizard.testing.ResourceHelpers;
import io.dropwizard.testing.junit5.DropwizardAppExtension;
import io.dropwizard.testing.junit5.DropwizardExtensionsSupport;
import com.dennyac.twirp.ErrorCode;
import com.dennyac.twirp.TwirpContext;
import com.dennyac.twirp.TwirpException;
import com.dennyac.twirp.TwirpClientBuilder;
import com.dennyac.twirp.TwirpMediaTypes;
import com.dennyac.twirp.example.haberdasher.Haberdasher;
import com.dennyac.twirp.example.haberdasher.HaberdasherClient;
import com.dennyac.twirp.example.haberdasher.Hat;
import com.dennyac.twirp.example.haberdasher.HatStyle;
import com.dennyac.twirp.example.haberdasher.Inventory;
import com.dennyac.twirp.example.haberdasher.InventoryRequest;
import com.dennyac.twirp.example.haberdasher.Size;
import com.dennyac.twirp.example.haberdasher.WhoAmIRequest;
import com.dennyac.twirp.example.haberdasher.WhoAmIResponse;
import jakarta.ws.rs.client.Client;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Exercises the {@code HaberdasherClient} generated by
 * {@code jaxrs-twirp-protoc} against the real example application.
 *
 * <p>Verifies the full client round trip: provider registration on the supplied
 * {@code WebTarget}, protobuf and JSON wire formats, and structured Twirp error
 * decoding so callers see {@link TwirpException} instead of raw HTTP errors.
 *
 * <p>Also demonstrates the runtime {@link TwirpClientBuilder} — the "managed
 * client builder" — which folds root-{@code WebTarget} resolution and content-type
 * selection into a fluent call so callers don't hand-build the target. It accepts
 * either a pre-built {@code Client} or an {@code Environment} + {@code
 * JerseyClientConfiguration}, all at test scope here so the example module keeps
 * {@code dropwizard-client} off its runtime classpath.
 */
@ExtendWith(DropwizardExtensionsSupport.class)
class GeneratedClientIntegrationTest {

    private static final DropwizardAppExtension<ExampleConfiguration> APP =
            new DropwizardAppExtension<>(
                    ExampleApplication.class,
                    ResourceHelpers.resourceFilePath("example.yml"),
                    ConfigOverride.config("server.applicationConnectors[0].port", "0"),
                    ConfigOverride.config("server.adminConnectors[0].port", "0"));

    // One Jersey client shared across tests — building one per test would spin up
    // a thread pool each time, which adds seconds and risks port exhaustion.
    // Built in @BeforeAll because APP.getEnvironment() isn't valid until the
    // extension has started the application.
    private static Client CLIENT;

    @BeforeAll
    static void buildClient() {
        CLIENT = new JerseyClientBuilder(APP.getEnvironment())
                .using(new JerseyClientConfiguration())
                .build("generated-client-it");
    }

    @AfterAll
    static void closeClient() {
        if (CLIENT != null) {
            CLIENT.close();
        }
    }

    @Test
    void protobufRoundTripViaGeneratedClient() throws TwirpException {
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()));

        Hat hat = remote.makeHat(
                Size.newBuilder().setInches(12).build(),
                TwirpContext.empty());

        // HaberdasherImpl maps 12" -> fedora.
        assertThat(hat.getInches()).isEqualTo(12);
        assertThat(hat.getStyleName()).isEqualTo("fedora");
        assertThat(hat.getColor()).isIn(Set.of("red", "blue", "green", "black", "brown"));
    }

    @Test
    void jsonRoundTripViaGeneratedClient() throws TwirpException {
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()),
                TwirpMediaTypes.APPLICATION_JSON);

        Hat hat = remote.makeHat(
                Size.newBuilder().setInches(7).build(),
                TwirpContext.empty());

        assertThat(hat.getInches()).isEqualTo(7);
        assertThat(hat.getStyleName()).isEqualTo("bowler");
    }

    @Test
    void serverErrorsSurfaceAsTwirpExceptionWithMeta() {
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()));

        // inches=0 trips the HaberdasherImpl precondition. We expect the wire
        // 400 + error envelope to be decoded into a typed exception by the
        // generated client, not bubble up as a JAX-RS exception.
        assertThatThrownBy(() -> remote.makeHat(
                Size.newBuilder().setInches(0).build(),
                TwirpContext.empty()))
                .isInstanceOfSatisfying(TwirpException.class, ex -> {
                    assertThat(ex.getErrorCode()).isEqualTo(ErrorCode.INVALID_ARGUMENT);
                    assertThat(ex.getMessage()).isEqualTo("inches must be > 0");
                    assertThat(ex.getMeta()).containsEntry("argument", "inches");
                });
    }

    @Test
    void listInventoryViaGeneratedClientCarriesEnumArrayAndMap() throws TwirpException {
        // The richer RPC (enum + repeated nested message + map) goes through the
        // exact same generated client. Exercise it in JSON mode to prove the
        // structured response decodes back into typed protobuf objects.
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()),
                TwirpMediaTypes.APPLICATION_JSON);

        Inventory inventory = remote.listInventory(
                InventoryRequest.newBuilder().setStyle(HatStyle.TOP_HAT).build(),
                TwirpContext.empty());

        assertThat(inventory.getItemsList()).hasSize(1);
        assertThat(inventory.getItemsList().get(0).getStyle()).isEqualTo(HatStyle.TOP_HAT);
        assertThat(inventory.getItemsList().get(0).getInches()).isEqualTo(14);
        assertThat(inventory.getCountByColorMap()).containsEntry("black", 1);
    }

    @Test
    void authenticatedWhoAmIForwardsBearerTokenAndReadsPrincipal() throws TwirpException {
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()));

        TwirpContext auth = TwirpContext.ofOutboundHeaders(
                Map.of("Authorization", List.of("Bearer admin-token")));
        WhoAmIResponse who = remote.whoAmI(WhoAmIRequest.getDefaultInstance(), auth);

        assertThat(who.getSubject()).isEqualTo("admin");
        assertThat(who.getAdmin()).isTrue();
    }

    @Test
    void authenticatedWhoAmINonAdminHasNoAdminRole() throws TwirpException {
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()));

        TwirpContext auth = TwirpContext.ofOutboundHeaders(
                Map.of("Authorization", List.of("Bearer user-token")));
        WhoAmIResponse who = remote.whoAmI(WhoAmIRequest.getDefaultInstance(), auth);

        assertThat(who.getSubject()).isEqualTo("alice");
        assertThat(who.getAdmin()).isFalse();
    }

    @Test
    void unauthenticatedWhoAmISurfacesAsUnauthenticated() {
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()));

        assertThatThrownBy(() ->
                remote.whoAmI(WhoAmIRequest.getDefaultInstance(), TwirpContext.empty()))
                .isInstanceOfSatisfying(TwirpException.class, ex ->
                        assertThat(ex.getErrorCode()).isEqualTo(ErrorCode.UNAUTHENTICATED));
    }

    @Test
    void networkErrorsSurfaceAsUnavailable() {
        // Point the client at a port nothing is listening on so the underlying
        // HTTP call fails. We expect TwirpClients.invoke to wrap the transport
        // failure as ErrorCode.UNAVAILABLE rather than throwing ProcessingException.
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:1"));

        assertThatThrownBy(() -> remote.makeHat(
                Size.newBuilder().setInches(7).build(),
                TwirpContext.empty()))
                .isInstanceOfSatisfying(TwirpException.class, ex ->
                        assertThat(ex.getErrorCode()).isEqualTo(ErrorCode.UNAVAILABLE));
    }

    @Test
    void managedBuilderProtobufRoundTrip() throws TwirpException {
        // The managed builder: hand it a Dropwizard-managed Client + a baseUri and
        // it resolves the root WebTarget and content type for you. No need to know
        // the generated constructor wants the *root* target — that footgun is gone.
        Haberdasher remote = TwirpClientBuilder.forService(HaberdasherClient::new)
                .using(CLIENT)
                .baseUri("http://localhost:" + APP.getLocalPort())
                .build();

        Hat hat = remote.makeHat(
                Size.newBuilder().setInches(12).build(),
                TwirpContext.empty());

        assertThat(hat.getInches()).isEqualTo(12);
        assertThat(hat.getStyleName()).isEqualTo("fedora");
    }

    @Test
    void managedBuilderJsonRoundTrip() throws TwirpException {
        // Same builder, JSON wire format selected fluently with .json().
        Haberdasher remote = TwirpClientBuilder.forService(HaberdasherClient::new)
                .using(CLIENT)
                .baseUri("http://localhost:" + APP.getLocalPort())
                .json()
                .build();

        Hat hat = remote.makeHat(
                Size.newBuilder().setInches(7).build(),
                TwirpContext.empty());

        assertThat(hat.getInches()).isEqualTo(7);
        assertThat(hat.getStyleName()).isEqualTo("bowler");
    }

    @Test
    void managedBuilderFromEnvironmentAndConfig() throws TwirpException {
        // The ergonomics the builder ultimately targets: no pre-built Client at
        // all. The builder spins up a Dropwizard-managed JerseyClient from the
        // app's Environment + a JerseyClientConfiguration, then wires the stub —
        // exactly HaberdasherClient.builder(environment, configuration) would do
        // when codegen is run with clientBuilder=true.
        Haberdasher remote = TwirpClientBuilder.forService(HaberdasherClient::new)
                .using(APP.getEnvironment(), new JerseyClientConfiguration())
                .baseUri("http://localhost:" + APP.getLocalPort())
                .clientName("managed-builder-it")
                .build();

        Hat hat = remote.makeHat(
                Size.newBuilder().setInches(7).build(),
                TwirpContext.empty());

        assertThat(hat.getStyleName()).isEqualTo("bowler");
    }
}
