package io.dropwizard.twirp.example;

import io.dropwizard.client.JerseyClientBuilder;
import io.dropwizard.client.JerseyClientConfiguration;
import io.dropwizard.testing.ConfigOverride;
import io.dropwizard.testing.ResourceHelpers;
import io.dropwizard.testing.junit5.DropwizardAppExtension;
import io.dropwizard.testing.junit5.DropwizardExtensionsSupport;
import io.dropwizard.twirp.ErrorCode;
import io.dropwizard.twirp.TwirpException;
import io.dropwizard.twirp.TwirpMediaTypes;
import io.dropwizard.twirp.example.haberdasher.Haberdasher;
import io.dropwizard.twirp.example.haberdasher.HaberdasherClient;
import io.dropwizard.twirp.example.haberdasher.Hat;
import io.dropwizard.twirp.example.haberdasher.Size;
import jakarta.ws.rs.client.Client;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Exercises the {@code HaberdasherClient} generated by
 * {@code dropwizard-twirp-protoc} against the real example application.
 *
 * <p>Verifies the full client round trip: provider registration on the supplied
 * {@code WebTarget}, protobuf and JSON wire formats, and structured Twirp error
 * decoding so callers see {@link TwirpException} instead of raw HTTP errors.
 */
@ExtendWith(DropwizardExtensionsSupport.class)
class GeneratedClientIntegrationTest {

    private static final DropwizardAppExtension<ExampleConfiguration> APP =
            new DropwizardAppExtension<>(
                    ExampleApplication.class,
                    ResourceHelpers.resourceFilePath("example.yml"),
                    ConfigOverride.config("server.applicationConnectors[0].port", "0"),
                    ConfigOverride.config("server.adminConnectors[0].port", "0"));

    // One Jersey client shared across tests — building one per test would spin up
    // a thread pool each time, which adds seconds and risks port exhaustion.
    // Built in @BeforeAll because APP.getEnvironment() isn't valid until the
    // extension has started the application.
    private static Client CLIENT;

    @BeforeAll
    static void buildClient() {
        CLIENT = new JerseyClientBuilder(APP.getEnvironment())
                .using(new JerseyClientConfiguration())
                .build("generated-client-it");
    }

    @AfterAll
    static void closeClient() {
        if (CLIENT != null) {
            CLIENT.close();
        }
    }

    @Test
    void protobufRoundTripViaGeneratedClient() throws TwirpException {
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()));

        Hat hat = remote.makeHat(Size.newBuilder().setInches(12).build());

        // HaberdasherImpl maps 12" -> fedora.
        assertThat(hat.getInches()).isEqualTo(12);
        assertThat(hat.getStyleName()).isEqualTo("fedora");
        assertThat(hat.getColor()).isIn(Set.of("red", "blue", "green", "black", "brown"));
    }

    @Test
    void jsonRoundTripViaGeneratedClient() throws TwirpException {
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()),
                TwirpMediaTypes.APPLICATION_JSON);

        Hat hat = remote.makeHat(Size.newBuilder().setInches(7).build());

        assertThat(hat.getInches()).isEqualTo(7);
        assertThat(hat.getStyleName()).isEqualTo("bowler");
    }

    @Test
    void serverErrorsSurfaceAsTwirpExceptionWithMeta() {
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:" + APP.getLocalPort()));

        // inches=0 trips the HaberdasherImpl precondition. We expect the wire
        // 400 + error envelope to be decoded into a typed exception by the
        // generated client, not bubble up as a JAX-RS exception.
        assertThatThrownBy(() -> remote.makeHat(Size.newBuilder().setInches(0).build()))
                .isInstanceOfSatisfying(TwirpException.class, ex -> {
                    assertThat(ex.getErrorCode()).isEqualTo(ErrorCode.INVALID_ARGUMENT);
                    assertThat(ex.getMessage()).isEqualTo("inches must be > 0");
                    assertThat(ex.getMeta()).containsEntry("argument", "inches");
                });
    }

    @Test
    void networkErrorsSurfaceAsUnavailable() {
        // Point the client at a port nothing is listening on so the underlying
        // HTTP call fails. We expect TwirpClients.invoke to wrap the transport
        // failure as ErrorCode.UNAVAILABLE rather than throwing ProcessingException.
        Haberdasher remote = new HaberdasherClient(
                CLIENT.target("http://localhost:1"));

        assertThatThrownBy(() -> remote.makeHat(Size.newBuilder().setInches(7).build()))
                .isInstanceOfSatisfying(TwirpException.class, ex ->
                        assertThat(ex.getErrorCode()).isEqualTo(ErrorCode.UNAVAILABLE));
    }
}
