/**
 * Dropwizard support for the
 * <a href="https://twitchtv.github.io/twirp/docs/spec_v7.html">Twirp RPC protocol (v7)</a>.
 *
 * <p>Install {@link io.dropwizard.twirp.TwirpBundle} in your application and
 * register Twirp resource classes (typically generated by
 * {@code dropwizard-twirp-protoc}) with the Jersey environment.
 */
package io.dropwizard.twirp;
