package io.dropwizard.twirp;

import com.google.protobuf.TypeRegistry;
import com.google.protobuf.util.JsonFormat;
import io.dropwizard.core.Configuration;
import io.dropwizard.core.ConfiguredBundle;
import io.dropwizard.core.setup.Environment;

import java.util.Objects;

/**
 * Dropwizard bundle that registers the Jersey providers required to serve Twirp
 * RPC endpoints from a regular Dropwizard application.
 *
 * <p>After installation, any resource class generated by {@code dropwizard-twirp-protoc}
 * will route incoming {@code POST /twirp/&lt;pkg&gt;.&lt;Service&gt;/&lt;Method&gt;} requests
 * to the supplied service implementation, with full support for both
 * {@code application/protobuf} and {@code application/json} bodies, and emit
 * Twirp-formatted JSON errors on failure.
 *
 * <p>Wire it into your application's {@code initialize} method:
 * <pre>{@code
 * @Override
 * public void initialize(Bootstrap<MyConfig> bootstrap) {
 *     bootstrap.addBundle(new TwirpBundle<>());
 * }
 *
 * @Override
 * public void run(MyConfig config, Environment env) {
 *     env.jersey().register(new HaberdasherResource(new MyHaberdasher()));
 * }
 * }</pre>
 *
 * <p>To customize the JSON printer/parser (for example to emit camelCase or skip
 * default fields), use {@link Builder}:
 * <pre>{@code
 * bootstrap.addBundle(TwirpBundle.builder()
 *     .jsonPrinter(JsonFormat.printer().includingDefaultValueFields())
 *     .build());
 * }</pre>
 *
 * <p>If any of your messages embed a {@code google.protobuf.Any}, JSON
 * serialization needs a {@link TypeRegistry} that knows the packed message
 * types (binary protobuf does not). Supply one with {@link Builder#typeRegistry}:
 * <pre>{@code
 * bootstrap.addBundle(TwirpBundle.builder()
 *     .typeRegistry(TypeRegistry.newBuilder()
 *         .add(MyPackedMessage.getDescriptor())
 *         .build())
 *     .build());
 * }</pre>
 *
 * @param <C> the application configuration type (any subclass of {@link Configuration})
 */
public class TwirpBundle<C extends Configuration> implements ConfiguredBundle<C> {

    private final JsonFormat.Printer jsonPrinter;
    private final JsonFormat.Parser jsonParser;

    public TwirpBundle() {
        this(defaultPrinter(), defaultParser());
    }

    public TwirpBundle(JsonFormat.Printer jsonPrinter, JsonFormat.Parser jsonParser) {
        this.jsonPrinter = Objects.requireNonNull(jsonPrinter, "jsonPrinter");
        this.jsonParser = Objects.requireNonNull(jsonParser, "jsonParser");
    }

    @Override
    public void run(C configuration, Environment environment) {
        environment.jersey().register(new TwirpServerFeature(jsonPrinter, jsonParser));
    }

    /**
     * The default JSON printer mirrors Twirp Go server defaults: snake_case
     * field names, zero-value fields included, no insignificant whitespace.
     */
    public static JsonFormat.Printer defaultPrinter() {
        return TwirpJson.defaultPrinter();
    }

    /** The default JSON parser silently ignores unknown fields. */
    public static JsonFormat.Parser defaultParser() {
        return TwirpJson.defaultParser();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private JsonFormat.Printer jsonPrinter = defaultPrinter();
        private JsonFormat.Parser jsonParser = defaultParser();
        private TypeRegistry typeRegistry;

        private Builder() {
        }

        public Builder jsonPrinter(JsonFormat.Printer printer) {
            this.jsonPrinter = Objects.requireNonNull(printer, "printer");
            return this;
        }

        public Builder jsonParser(JsonFormat.Parser parser) {
            this.jsonParser = Objects.requireNonNull(parser, "parser");
            return this;
        }

        /**
         * Register a {@link TypeRegistry} so that messages embedding a
         * {@code google.protobuf.Any} can be serialized to and parsed from JSON.
         * The registry is applied to both the printer and the parser at
         * {@link #build} time, preserving their other settings.
         *
         * <p>Only needed for the JSON wire format — binary protobuf carries the
         * {@code Any} type URL inline and needs no registry. Do not combine this
         * with a custom {@link #jsonPrinter}/{@link #jsonParser} that already has
         * a registry of its own; supply the registry through exactly one path.
         */
        public Builder typeRegistry(TypeRegistry registry) {
            this.typeRegistry = Objects.requireNonNull(registry, "registry");
            return this;
        }

        public <C extends Configuration> TwirpBundle<C> build() {
            JsonFormat.Printer printer = jsonPrinter;
            JsonFormat.Parser parser = jsonParser;
            if (typeRegistry != null) {
                printer = printer.usingTypeRegistry(typeRegistry);
                parser = parser.usingTypeRegistry(typeRegistry);
            }
            return new TwirpBundle<>(printer, parser);
        }
    }
}
