package io.dropwizard.twirp;

import com.google.protobuf.util.JsonFormat;
import io.dropwizard.core.Configuration;
import io.dropwizard.core.ConfiguredBundle;
import io.dropwizard.core.setup.Environment;
import io.dropwizard.twirp.codec.ProtobufJsonMessageBodyReader;
import io.dropwizard.twirp.codec.ProtobufJsonMessageBodyWriter;
import io.dropwizard.twirp.codec.ProtobufMessageBodyReader;
import io.dropwizard.twirp.codec.ProtobufMessageBodyWriter;
import io.dropwizard.twirp.errors.InvalidProtocolBufferExceptionMapper;
import io.dropwizard.twirp.errors.TwirpExceptionMapper;

import java.util.Objects;

/**
 * Dropwizard bundle that registers the Jersey providers required to serve Twirp
 * RPC endpoints from a regular Dropwizard application.
 *
 * <p>After installation, any resource class generated by {@code dropwizard-twirp-protoc}
 * will route incoming {@code POST /twirp/&lt;pkg&gt;.&lt;Service&gt;/&lt;Method&gt;} requests
 * to the supplied service implementation, with full support for both
 * {@code application/protobuf} and {@code application/json} bodies, and emit
 * Twirp-formatted JSON errors on failure.
 *
 * <p>Wire it into your application's {@code initialize} method:
 * <pre>{@code
 * @Override
 * public void initialize(Bootstrap<MyConfig> bootstrap) {
 *     bootstrap.addBundle(new TwirpBundle<>());
 * }
 *
 * @Override
 * public void run(MyConfig config, Environment env) {
 *     env.jersey().register(new HaberdasherResource(new MyHaberdasher()));
 * }
 * }</pre>
 *
 * <p>To customize the JSON printer/parser (for example to emit camelCase or skip
 * default fields), use {@link Builder}:
 * <pre>{@code
 * bootstrap.addBundle(TwirpBundle.builder()
 *     .jsonPrinter(JsonFormat.printer().includingDefaultValueFields())
 *     .build());
 * }</pre>
 *
 * @param <C> the application configuration type (any subclass of {@link Configuration})
 */
public class TwirpBundle<C extends Configuration> implements ConfiguredBundle<C> {

    private final JsonFormat.Printer jsonPrinter;
    private final JsonFormat.Parser jsonParser;

    public TwirpBundle() {
        this(defaultPrinter(), defaultParser());
    }

    public TwirpBundle(JsonFormat.Printer jsonPrinter, JsonFormat.Parser jsonParser) {
        this.jsonPrinter = Objects.requireNonNull(jsonPrinter, "jsonPrinter");
        this.jsonParser = Objects.requireNonNull(jsonParser, "jsonParser");
    }

    @Override
    public void run(C configuration, Environment environment) {
        environment.jersey().register(new ProtobufMessageBodyReader());
        environment.jersey().register(new ProtobufMessageBodyWriter());
        environment.jersey().register(new ProtobufJsonMessageBodyReader(jsonParser));
        environment.jersey().register(new ProtobufJsonMessageBodyWriter(jsonPrinter));
        environment.jersey().register(new TwirpExceptionMapper());
        environment.jersey().register(new InvalidProtocolBufferExceptionMapper());
    }

    /**
     * The default JSON printer mirrors Twirp Go server defaults: snake_case
     * field names, zero-value fields included, no insignificant whitespace.
     */
    public static JsonFormat.Printer defaultPrinter() {
        return JsonFormat.printer()
                .preservingProtoFieldNames()
                .includingDefaultValueFields()
                .omittingInsignificantWhitespace();
    }

    /** The default JSON parser silently ignores unknown fields. */
    public static JsonFormat.Parser defaultParser() {
        return JsonFormat.parser().ignoringUnknownFields();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private JsonFormat.Printer jsonPrinter = defaultPrinter();
        private JsonFormat.Parser jsonParser = defaultParser();

        private Builder() {
        }

        public Builder jsonPrinter(JsonFormat.Printer printer) {
            this.jsonPrinter = Objects.requireNonNull(printer, "printer");
            return this;
        }

        public Builder jsonParser(JsonFormat.Parser parser) {
            this.jsonParser = Objects.requireNonNull(parser, "parser");
            return this;
        }

        public <C extends Configuration> TwirpBundle<C> build() {
            return new TwirpBundle<>(jsonPrinter, jsonParser);
        }
    }
}
