package io.dropwizard.twirp.protoc;

import com.google.protobuf.DescriptorProtos.MethodDescriptorProto;
import com.google.protobuf.DescriptorProtos.ServiceDescriptorProto;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import javax.lang.model.element.Modifier;

/**
 * Emits the server-side service interface for a Twirp service.
 *
 * <p>For a proto service {@code Haberdasher} with an RPC
 * {@code MakeHat(Size) returns (Hat)}, this generates:
 *
 * <pre>{@code
 * public interface Haberdasher {
 *     Hat makeHat(Size request) throws TwirpException;
 * }
 * }</pre>
 *
 * <p>Method names are lowerCamelCase Java equivalents of the proto RPC names.
 * Streaming RPCs are not supported (Twirp itself doesn't support them) and will
 * cause an exception during generation.
 */
final class ServiceGenerator {

    private static final ClassName TWIRP_EXCEPTION =
            ClassName.get("io.dropwizard.twirp", "TwirpException");

    private final TypeMapper types;

    ServiceGenerator(TypeMapper types) {
        this.types = types;
    }

    TypeSpec generateInterface(ServiceDescriptorProto service) {
        TypeSpec.Builder iface = TypeSpec.interfaceBuilder(service.getName())
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Server-side interface for the {@code $L} Twirp service.\n"
                        + "\n<p>Generated by twirp-protoc — do not edit by hand.\n",
                        service.getName());

        for (MethodDescriptorProto method : service.getMethodList()) {
            if (method.getClientStreaming() || method.getServerStreaming()) {
                throw new IllegalArgumentException("streaming RPCs are not supported by Twirp ("
                        + service.getName() + "." + method.getName() + ")");
            }
            iface.addMethod(generateMethod(method));
        }
        return iface.build();
    }

    private MethodSpec generateMethod(MethodDescriptorProto method) {
        ClassName input = types.resolve(method.getInputType());
        ClassName output = types.resolve(method.getOutputType());
        String methodName = JavaNaming.lowerCamelMethodName(method.getName());

        return MethodSpec.methodBuilder(methodName)
                .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                .returns(output)
                .addParameter(input, "request")
                .addException(TWIRP_EXCEPTION)
                .build();
    }
}
